[package]
name = "rust_des"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
rand = "0.8"
combinatorial = "0.2.0"
array2d = "0.3.2"